export const giftShopNavigation = [
  {
    category: "Top Categories",
    categoryItem: [
      {
        icon: "Children",
        title: "Modern Art",
        href: "/product/search/Fruits & Vegetables",
      },
      {
        icon: "Chirstmas",
        title: "Artistic Prints",
        href: "/product/search/Dariry & Eggs",
      },
      {
        icon: "Flower",
        title: "Classic Flowers",
        href: "/product/search/Dariry & Eggs",
      },
      {
        icon: "TeddyBear",
        title: "Moditerranean Print",
        href: "/product/search/Breakfast",
      },
      {
        icon: "ValentineGift",
        title: "Ancient Maps",
        href: "/product/search/Frozen",
      },
      {
        icon: "WeddingGift",
        title: "Mid-century Patterns",
        href: "/product/search/Organic",
      },
      {
        icon: "NewYearGift",
        title: "Nature, Landscapes",
        href: "/product/search/Canned Food",
      },
      {
        icon: "Toys",
        title: "Animal Prints",
        href: "/product/search/Coffee & Snacks",
      },
      {
        icon: "Football",
        title: "Plup Art, Electric",
        href: "/product/search/Sauces & Jems",
      },
      {
        icon: "BabyToys",
        title: "Zodiac & Astrology",
        href: "/product/search/Sauces & Jems",
      },
      {
        icon: "Robot",
        title: "Music Lovers",
        href: "/product/search/Sauces & Jems",
      },
    ],
  },
];
export const serviceList = [
  {
    icon: "Truck",
    title: "Delivery quality lamps",
    subtitle1: "information on its origins",
    subtitle2: "centric approach",
  },
  {
    icon: "PickUpBox",
    title: "Lamps for Decoration",
    subtitle1: "information on its origins",
    subtitle2: "centric approach",
  },
  {
    icon: "OnlineService",
    title: "Happy Service",
    subtitle1: "information on its origins",
    subtitle2: "centric approach",
  },
];
export const topCategories = [
  {
    title: "NASA Lamp",
    available: "27 Available Items",
    imgUrl: "/assets/images/Gift Shop/lamp1.png",
  },
  {
    title: "Geometric Pattern Tripod...",
    available: "17 Available Items",
    imgUrl: "/assets/images/Gift Shop/lamp2.png",
  },
  {
    title: "Floral Tile Tripod Lamp...",
    available: "27 Available Items",
    imgUrl: "/assets/images/Gift Shop/lamp3.png",
  },
];
export const popularProducts = [
  {
    price: 162,
    title: "Modern Grayscale Tripod...",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampPI1.png",
    discount: 8,
    id: 7544411360,
  },
  {
    price: 98,
    title: "Rose Bloom Tripod Lamp...",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampPI2.png",
    discount: 11,
    id: 6808422238,
  },
  {
    price: 85,
    title: "Sunflower Table Lamp...",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampPI3.png",
    discount: 13,
    id: 8643586433,
  },
  {
    price: 218,
    title: "Tripod Lamp, Psychedelic...",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampPI4.png",
    discount: 11,
    id: 5666445442,
  },
  {
    price: 142,
    title: "Tripod Lamp",
    rating: 4,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampPI5.png",
    discount: 12,
    id: 3938759640,
  },
  {
    price: 71,
    title: "Tripod Lamp",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampPI2.png",
    discount: 8,
    id: 7101230747,
  },
];
export const topSailedProducts = [
  {
    price: 219,
    title: "Tripod Lamp",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampTS1.png",
    discount: 9,
    id: 6503013484,
  },
  {
    price: 209,
    title: "Tripod Lamp",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampTS3.png",
    discount: 17,
    id: 1042471944,
  },
  {
    price: 248,
    title: "Tripod Lamp",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampTS2.png",
    discount: 9,
    id: 1263502673,
  },
  {
    price: 111,
    title: "Tripod Lamp",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampTS3.png",
    discount: 12,
    id: 5884344952,
  },
  {
    price: 65,
    title: "Tripod Lamp",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampTS2.png",
    discount: 18,
    id: 8634030972,
  },
  {
    price: 71,
    title: "Tripod Lamp",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampTS1.png",
    discount: 8,
    id: 7101230747,
  },
];
export const giftShopProducts = [
  {
    price: 219,
    title: "Atomic Pattern Table Lamp, Mid...",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampPI5.png",
    discount: 9,
    id: 6503013484,
  },
  {
    price: 209,
    title: "Music Table Lamp, Printed Lamp Shades",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampPI8.png",
    discount: 17,
    id: 1042471944,
  },
  {
    price: 248,
    title: "Lovely Garden Tripod Lamp, Floral...",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampPI9.png",
    discount: 9,
    id: 1263502673,
  },
  {
    price: 111,
    title: "Atomic Pattern Lamp",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampP11.png",
    discount: 12,
    id: 5884344952,
  },
  {
    price: 65,
    title: "Atomic Pattern Lamp",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampP12.png",
    discount: 18,
    id: 8634030972,
  },
  {
    price: 71,
    title: "Atomic Pattern Lamp",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampP13.png",
    discount: 8,
    id: 7101230747,
  },
  {
    price: 172,
    title: "JAtomic Pattern Lamp",
    rating: 4,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lamp1.png",
    discount: 18,
    id: 3376292520,
  },
  {
    price: 162,
    title: "Atomic Pattern Lamp",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lamp2.png",
    discount: 8,
    id: 7544411360,
  },
  {
    price: 98,
    title: "Atomic Pattern Lamp",
    rating: 3,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lamp3.png",
    discount: 11,
    id: 6808422238,
  },
  {
    price: 85,
    title: "Atomic Pattern Lamp",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampTS1.png",
    discount: 13,
    id: 8643586433,
  },
  {
    price: 218,
    title: "Atomic Pattern Lamp",
    rating: 5,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampTS3.png",
    discount: 11,
    id: 5666445442,
  },
  {
    price: 142,
    title: "Atomic Pattern Lamp",
    rating: 4,
    category: "giftshop",
    imgUrl: "/assets/images/Gift Shop/lampP12.png",
    discount: 12,
    id: 3938759640,
  },
];
